### ISSUE TITLE
urlencoded document contents can't be handled by the service

### ISSUE THREAD

**Issue by markushausammann** [expectedbehavior/php-docraptor#11]
The wrapper currently does `urlencode()` on the content that is sent to DR.

https://github.com/expectedbehavior/php-docraptor/blob/master/src/DocRaptor.php#L176

But DR doesn't decode and instead just prints the whole content as a string. Is that **expectedbehavior** :smirk: or would it make sense to decode encoded strings?

**Comment by janxious** [comment]
Can you give me an example of what you're seeing?

**Comment by markushausammann** [comment]
![](https://www.evernote.com/shard/s57/sh/d9678a84-f717-41e2-b05e-f974230d349c/49d385018595be789056192d54a88b40/deep/0/test.pdf-%281-Seite%29-und-php-docraptor---markus@fantastico-----bash---112-34-und-Toggl-Desktop-und-iTunes.png)

**Comment by markushausammann** [comment]
If I remove the urlencode, everything looks nice.

**Comment by janxious** [comment]
I **think** what is happening is http://php.net/manual/en/function.http-build-query.php is encoding it a second time.

**Comment by janxious** [comment]
So yeah, we can probably remove that.

**Comment by markushausammann** [comment]
Ah yeah, that's it, sure. We either have to switch off the implicit call in the http_build_query (if possible) or write a comment, otherwise it looks as if it's not encoded. I'll take care of it.

**Comment by janxious** [comment]
I would much rather we rely on `http_build_query`.

**Comment by markushausammann** [comment]
Ok, let's just add a comment to the other line explaining why there is no urlencode call there.
