### ISSUE TITLE
Test public API

### ISSUE THREAD

**Issue by markushausammann** [expectedbehavior/php-docraptor#17]

**Comment by markushausammann** [comment]
Partly accomplished.

**Comment by markushausammann** [comment]
Depends on #21

**Comment by markushausammann** [comment]
The actual `ApiWrapper` has a coverage of 77% and basically only simple setters are not tested. So for the moment I think that's enough. If we wanted to go a step further, we would need to integreation test with a mock service, I don't think that's necessary at the moment.

**Comment by janxious** [comment]
Agree. Nice work!
