### ISSUE TITLE
PHP Versions - where to draw the line?

### ISSUE THREAD

**Issue by markushausammann** [expectedbehavior/php-docraptor#24]
Obviously PHP 5.3 is past EOL and 5.4 will have EOL soon too but right now according to my knowledge as well as the tests we have, it works with both. Also, part of the PHP community is known to be quite slow in adapting to new versions. On the other hand I wouldn't want to hold back with using newer features just because of supporting these versions.

I would propose to really drop 5.3 (everyone of "note" would advice to do so) but maybe keep 5.4 support until EOL is reached. I would add `nightly` though, which is basically an alias of PHP 7 (or vice versa).

**Comment by janxious** [comment]
Yeah, I think dropping `5.3` is fine now and 5.4 when it EOLs is also fine. `nightly`was in the list before, and I would be happy to have it back in. I doubt we are going to be using features that break very often. :smiley_cat:

Aside, if there is something like legacy support for old php versions where they get backported security updates, I am also fine with that. Something like that happened with ruby 1.8.x
